from typing import Any

__version__: str
EVENT_READ: int
EVENT_WRITE: int

class Worker:
    """A Tokio runtime serving ASGI or WSGI, driven as an asyncio selector.

    Every method but `wakeup` must be called from the thread that created it.
    """

    def __init__(self) -> None: ...
    def select(self, timeout: float | None = None, /) -> list[tuple[int, int]]: ...
    def register(self, fd: int, events: int, /) -> None: ...
    def modify(self, fd: int, events: int, /) -> None: ...
    def unregister(self, fd: int, /) -> None: ...
    def wakeup(self) -> None: ...
    def serve(self, sock_fd: int, app: Any, loop: Any, options: dict[str, Any] | None, /) -> None: ...
    def shutdown(self) -> None: ...
    def drain(self) -> None: ...
    def connections(self) -> int: ...
    def close(self) -> None: ...
